### ISSUE TITLE
메모장 창(?) 오류

### ISSUE THREAD

**Issue by Temaca333** [junhg0211/SloOS#17]
(이름 까먹음) 아무튼
메모장 창을 실행하고 나서 창을 최대한으로 최소화 할 경우 아래와 같은 오류 발생 하며 튕김

```python
Traceback (most recent call last):
  File ".\src\Main.pyw", line 192, in <module>                                                                              obj.tick()
  File "F:\Slo_OS\SloOS-master\src\rootobject\buckerwindow\buckerwindow.py", line 154, in tick
    self.build_surface()
  File "F:\Slo_OS\SloOS-master\src\rootobject\buckerwindow\buckerwindow.py", line 174, in build_surface
    self.surface = pygame.Surface((self.width - 2, self.height - 1 - self.title_height))                                pygame.error: Invalid resolution for Surface
```

**Comment by junhg0211** [comment]
@Temaca333 Slo Ogünemay 6.5.3 업데이트로 해결 했습니다 안녕!!!
