### ISSUE TITLE
오랫동안 창 움직일 때 에러 발생함

### ISSUE THREAD

**Issue by junhg0211** [junhg0211/SloOS#3]
```python
Traceback (most recent call last):
  File ".\Main.pyw", line 662, in <module>
    obj.tick()
  File ".\Main.pyw", line 448, in tick
    self.dock_y += (self.dock_y_target - self.dock_y) / (root.display.display_fps / slo.slo['appearance']['motion_speed'])
ZeroDivisionError: float division by zero
```
오랫동안 창 움직이고 있다가 놓으면 FPS 0 돼서 `ZeroDivisionError` 뜸.

**Comment by junhg0211** [comment]
tick-render 부분에 프레임 0일 때 작동 안 하는 if문 걸어서 해결했습니당
